Repository jimbrig/lossrx, pull requests merged in 2023-03, with the labels that each got.

#43 Update GitHub Action Versions
  .github/workflows/check.yml
  .github/workflows/coverage.yml
  .github/workflows/docker.yml
  .github/workflows/gh-release.yml
  .github/workflows/gha-versions.yml
  .github/workflows/git-cliff.yml
  .github/workflows/labels.yml
  .github/workflows/linguist.yml
  .github/workflows/pkgdown.yml
  .github/workflows/toc.yml
Labels: cicd

#42 Updated elgohr/Publish-Docker-Github-Action to a supported version (v5)
  .github/workflows/docker.yml
Labels: bug, config, cicd

#29 Preliminary Plumber API Setup
  inst/api/Dockerfile
  inst/api/README.md
  inst/api/openapi.yml
  inst/api/plumber.R
  inst/api/run_api.sh
Labels: api
